import Foundation

// MARK: - Exercise Seed Data
// 25 exercises covering all major muscle groups.
// Called once on first launch via SwiftDataService.

enum ExerciseSeedData {
    static func all() -> [Exercise] {
        [
            // MARK: Chest (5)
            Exercise(name: "Push-Up",
                     description: "A classic bodyweight exercise that targets the chest, shoulders, and triceps.",
                     instructions: ["Start in a high plank with hands shoulder-width apart",
                                    "Lower your chest to just above the floor",
                                    "Push back up to starting position",
                                    "Keep your core tight throughout"],
                     tips: ["Don't let your hips sag", "Keep elbows at 45° from your torso"],
                     primaryMuscles: [.chest],
                     secondaryMuscles: [.shoulders, .triceps],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Bodyweight",
                     iconName: "figure.strengthtraining.functional",
                     caloriesPerMinute: 7),

            Exercise(name: "Bench Press",
                     description: "The gold-standard chest builder using a barbell.",
                     instructions: ["Lie flat on bench, grip bar just outside shoulder width",
                                    "Unrack and lower bar to mid-chest with control",
                                    "Press back up explosively",
                                    "Lock out elbows at top"],
                     tips: ["Keep shoulder blades retracted and depressed", "Drive feet into the floor"],
                     primaryMuscles: [.chest],
                     secondaryMuscles: [.shoulders, .triceps],
                     category: .strength,
                     difficulty: .intermediate,
                     equipment: "Barbell",
                     iconName: "dumbbell.fill",
                     caloriesPerMinute: 6),

            Exercise(name: "Dumbbell Fly",
                     description: "Isolation exercise for the chest, focusing on the stretch.",
                     instructions: ["Lie on bench with dumbbells above chest, palms facing",
                                    "Lower arms out to sides with slight elbow bend",
                                    "Feel a deep stretch at the bottom",
                                    "Squeeze chest to bring dumbbells back together"],
                     tips: ["Never fully straighten elbows", "Control the descent"],
                     primaryMuscles: [.chest],
                     secondaryMuscles: [.shoulders],
                     category: .hypertrophy,
                     difficulty: .intermediate,
                     equipment: "Dumbbells",
                     iconName: "dumbbell.fill",
                     caloriesPerMinute: 5),

            Exercise(name: "Incline Dumbbell Press",
                     description: "Upper chest developer at a 30-45° incline.",
                     instructions: ["Set bench to 30-45° incline",
                                    "Hold dumbbells at shoulder level",
                                    "Press upward and slightly inward",
                                    "Lower with control"],
                     tips: ["Don't exceed 45° — it shifts load to shoulders"],
                     primaryMuscles: [.chest],
                     secondaryMuscles: [.shoulders, .triceps],
                     category: .hypertrophy,
                     difficulty: .intermediate,
                     equipment: "Dumbbells",
                     iconName: "dumbbell.fill",
                     caloriesPerMinute: 6),

            Exercise(name: "Dips",
                     description: "Upper body compound that hits chest, triceps, and shoulders.",
                     instructions: ["Grip parallel bars, arms fully extended",
                                    "Lean forward slightly and lower until elbows at 90°",
                                    "Press back up to full extension"],
                     tips: ["Lean forward more for more chest, upright for more triceps"],
                     primaryMuscles: [.chest, .triceps],
                     secondaryMuscles: [.shoulders],
                     category: .strength,
                     difficulty: .intermediate,
                     equipment: "Bodyweight",
                     iconName: "figure.strengthtraining.functional",
                     caloriesPerMinute: 7),

            // MARK: Back (5)
            Exercise(name: "Pull-Up",
                     description: "The king of back exercises — pulls the entire posterior chain.",
                     instructions: ["Hang from bar with overhand grip, shoulder-width",
                                    "Pull chest toward bar, leading with elbows",
                                    "Lower with control to full hang"],
                     tips: ["Dead hang at bottom for full range", "Avoid kipping unless trained"],
                     primaryMuscles: [.back],
                     secondaryMuscles: [.biceps],
                     category: .strength,
                     difficulty: .intermediate,
                     equipment: "Pull-up Bar",
                     iconName: "figure.climbing",
                     caloriesPerMinute: 8),

            Exercise(name: "Bent-Over Row",
                     description: "Barbell row for dense back thickness.",
                     instructions: ["Hinge at hips to ~45°, grip bar shoulder-width",
                                    "Pull bar to lower chest/upper abs",
                                    "Squeeze shoulder blades together at top",
                                    "Lower with control"],
                     tips: ["Keep lower back flat — don't round", "Lead with elbows, not hands"],
                     primaryMuscles: [.back],
                     secondaryMuscles: [.biceps, .core],
                     category: .strength,
                     difficulty: .intermediate,
                     equipment: "Barbell",
                     iconName: "figure.rowing",
                     caloriesPerMinute: 7),

            Exercise(name: "Deadlift",
                     description: "The ultimate posterior chain exercise — total body strength builder.",
                     instructions: ["Bar over mid-foot, hip-width stance",
                                    "Hinge and grip bar just outside knees",
                                    "Brace core, chest up — drive floor away with legs",
                                    "Hips and shoulders rise together",
                                    "Stand tall, then hinge to lower"],
                     tips: ["Never round your lower back", "Push the floor down, don't pull up"],
                     primaryMuscles: [.back, .glutes, .hamstrings],
                     secondaryMuscles: [.core, .quadriceps],
                     category: .strength,
                     difficulty: .advanced,
                     equipment: "Barbell",
                     iconName: "figure.strengthtraining.traditional",
                     caloriesPerMinute: 9),

            Exercise(name: "Lat Pulldown",
                     description: "Cable machine back builder, great for beginners before pull-ups.",
                     instructions: ["Grip bar wider than shoulders, sit with thighs secured",
                                    "Pull bar to upper chest, leading with elbows",
                                    "Lean back slightly at bottom",
                                    "Let bar rise with control"],
                     tips: ["Avoid pulling behind the neck — increases injury risk"],
                     primaryMuscles: [.back],
                     secondaryMuscles: [.biceps],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Cable Machine",
                     iconName: "figure.rowing",
                     caloriesPerMinute: 6),

            Exercise(name: "Face Pull",
                     description: "Rear delt and rotator cuff health exercise with cable.",
                     instructions: ["Set cable at head height with rope attachment",
                                    "Pull rope toward face, external rotating at end",
                                    "Pause at peak contraction",
                                    "Return slowly"],
                     tips: ["Great for shoulder health — don't skip this", "Keep elbows high"],
                     primaryMuscles: [.shoulders, .back],
                     secondaryMuscles: [],
                     category: .mobility,
                     difficulty: .beginner,
                     equipment: "Cable Machine",
                     iconName: "figure.arms.open",
                     caloriesPerMinute: 5),

            // MARK: Shoulders (3)
            Exercise(name: "Overhead Press",
                     description: "Barbell shoulder press — king of shoulder mass builders.",
                     instructions: ["Grip bar just outside shoulders, bar resting on upper chest",
                                    "Press bar overhead to full lockout",
                                    "Lower under control to starting position"],
                     tips: ["Brace your core hard", "Don't lean back excessively"],
                     primaryMuscles: [.shoulders],
                     secondaryMuscles: [.triceps, .core],
                     category: .strength,
                     difficulty: .intermediate,
                     equipment: "Barbell",
                     iconName: "figure.arms.open",
                     caloriesPerMinute: 7),

            Exercise(name: "Lateral Raise",
                     description: "Dumbbell side raises for medial delt width.",
                     instructions: ["Stand with dumbbells at sides",
                                    "Raise arms out to sides to shoulder height",
                                    "Lead with pinkies for better activation",
                                    "Lower slowly"],
                     tips: ["Lighter weight, strict form beats heavy and swinging"],
                     primaryMuscles: [.shoulders],
                     secondaryMuscles: [],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Dumbbells",
                     iconName: "figure.arms.open",
                     caloriesPerMinute: 5),

            Exercise(name: "Arnold Press",
                     description: "Rotational dumbbell press that hits all three delt heads.",
                     instructions: ["Start with dumbbells at chin height, palms facing you",
                                    "As you press up, rotate palms outward",
                                    "Full rotation by time arms are extended",
                                    "Reverse rotation on the way down"],
                     tips: ["Arnold himself used this for complete shoulder development"],
                     primaryMuscles: [.shoulders],
                     secondaryMuscles: [.triceps],
                     category: .hypertrophy,
                     difficulty: .intermediate,
                     equipment: "Dumbbells",
                     iconName: "figure.arms.open",
                     caloriesPerMinute: 6),

            // MARK: Arms (3)
            Exercise(name: "Barbell Curl",
                     description: "Classic bicep builder with maximum overload potential.",
                     instructions: ["Stand with barbell, underhand grip shoulder-width",
                                    "Curl bar up keeping elbows stationary",
                                    "Squeeze at top",
                                    "Lower slowly — the negative builds mass"],
                     tips: ["Don't swing — stand against a wall if needed"],
                     primaryMuscles: [.biceps],
                     secondaryMuscles: [],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Barbell",
                     iconName: "figure.curling",
                     caloriesPerMinute: 5),

            Exercise(name: "Tricep Skull Crusher",
                     description: "EZ-bar or dumbbell tricep isolation lying on bench.",
                     instructions: ["Lie on bench, arms extended above chest",
                                    "Bend only at elbows, lowering weight toward forehead",
                                    "Extend back to start without flaring elbows"],
                     tips: ["Keep upper arms perfectly vertical"],
                     primaryMuscles: [.triceps],
                     secondaryMuscles: [],
                     category: .hypertrophy,
                     difficulty: .intermediate,
                     equipment: "EZ-Bar",
                     iconName: "figure.gymnastics",
                     caloriesPerMinute: 5),

            Exercise(name: "Hammer Curl",
                     description: "Neutral-grip curl hitting brachialis and brachioradialis.",
                     instructions: ["Hold dumbbells with neutral grip (thumbs up)",
                                    "Curl keeping palms facing each other throughout",
                                    "Lower with control"],
                     tips: ["Excellent for arm thickness and forearm development"],
                     primaryMuscles: [.biceps],
                     secondaryMuscles: [],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Dumbbells",
                     iconName: "figure.curling",
                     caloriesPerMinute: 5),

            // MARK: Legs (5)
            Exercise(name: "Back Squat",
                     description: "The king of leg exercises — total lower body builder.",
                     instructions: ["Bar on upper back, feet shoulder-width, toes out slightly",
                                    "Brace core and squat until thighs parallel to floor",
                                    "Drive knees out and push through heels to stand",
                                    "Stay upright — don't collapse forward"],
                     tips: ["Heels elevated slightly helps if mobility is limited", "Depth over weight"],
                     primaryMuscles: [.quadriceps, .glutes],
                     secondaryMuscles: [.hamstrings, .core],
                     category: .strength,
                     difficulty: .intermediate,
                     equipment: "Barbell",
                     iconName: "figure.step.training",
                     caloriesPerMinute: 9),

            Exercise(name: "Romanian Deadlift",
                     description: "Hip-hinge movement focusing on hamstrings and glutes.",
                     instructions: ["Stand with bar at hip height",
                                    "Hinge at hips, pushing them back as bar slides down legs",
                                    "Feel hamstring stretch — go as low as mobility allows",
                                    "Drive hips forward to stand"],
                     tips: ["Soft knee bend only — not a squat", "Bar stays in contact with legs"],
                     primaryMuscles: [.hamstrings, .glutes],
                     secondaryMuscles: [.back],
                     category: .hypertrophy,
                     difficulty: .intermediate,
                     equipment: "Barbell",
                     iconName: "figure.step.training",
                     caloriesPerMinute: 8),

            Exercise(name: "Walking Lunges",
                     description: "Unilateral leg exercise for quad, glute, and balance.",
                     instructions: ["Step forward into lunge, knee tracking over toes",
                                    "Lower back knee toward floor",
                                    "Drive front heel to stand and step through",
                                    "Alternate legs with each step"],
                     tips: ["Stay upright — don't lean forward"],
                     primaryMuscles: [.quadriceps, .glutes],
                     secondaryMuscles: [.hamstrings, .calves],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Bodyweight",
                     iconName: "figure.walk",
                     caloriesPerMinute: 7),

            Exercise(name: "Hip Thrust",
                     description: "The best glute isolation exercise with barbell load.",
                     instructions: ["Sit against bench, bar on hip crease",
                                    "Drive hips up until body is parallel to floor",
                                    "Squeeze glutes hard at the top",
                                    "Lower with control"],
                     tips: ["Chin tucked — don't hyperextend the neck"],
                     primaryMuscles: [.glutes],
                     secondaryMuscles: [.hamstrings],
                     category: .hypertrophy,
                     difficulty: .intermediate,
                     equipment: "Barbell",
                     iconName: "figure.step.training",
                     caloriesPerMinute: 7),

            Exercise(name: "Calf Raise",
                     description: "Standing calf raises for gastrocnemius and soleus.",
                     instructions: ["Stand on edge of step, heels hanging off",
                                    "Rise up on toes as high as possible",
                                    "Pause for 1s at top",
                                    "Lower heels below step level for full stretch"],
                     tips: ["Full range of motion is key — short bounces don't work"],
                     primaryMuscles: [.calves],
                     secondaryMuscles: [],
                     category: .hypertrophy,
                     difficulty: .beginner,
                     equipment: "Bodyweight",
                     iconName: "figure.step.training",
                     caloriesPerMinute: 4),

            // MARK: Core (2)
            Exercise(name: "Plank",
                     description: "Isometric core stability exercise — the foundation of a strong core.",
                     instructions: ["Forearms on floor, body in straight line from head to heels",
                                    "Brace abs as if taking a punch",
                                    "Hold for target duration",
                                    "Breathe — don't hold your breath"],
                     tips: ["Squeeze glutes and quads too for full body tension"],
                     primaryMuscles: [.core],
                     secondaryMuscles: [.shoulders],
                     category: .strength,
                     difficulty: .beginner,
                     equipment: "Bodyweight",
                     defaultDurationSeconds: 60,
                     iconName: "figure.core.training",
                     caloriesPerMinute: 4),

            Exercise(name: "Hanging Leg Raise",
                     description: "Advanced core exercise targeting lower abs and hip flexors.",
                     instructions: ["Hang from pull-up bar with full grip",
                                    "Raise legs keeping them straight until parallel to floor",
                                    "Lower with control — don't swing"],
                     tips: ["Posterior pelvic tilt at top for better ab activation"],
                     primaryMuscles: [.core],
                     secondaryMuscles: [],
                     category: .strength,
                     difficulty: .advanced,
                     equipment: "Pull-up Bar",
                     iconName: "figure.core.training",
                     caloriesPerMinute: 6),

            // MARK: Cardio (2)
            Exercise(name: "Burpee",
                     description: "Full body HIIT movement — maximum calorie burn in minimum time.",
                     instructions: ["Stand, then drop hands to floor",
                                    "Jump or step feet back to plank",
                                    "Optional push-up",
                                    "Jump feet to hands",
                                    "Explode up with arms overhead"],
                     tips: ["Modify by stepping instead of jumping to scale down"],
                     primaryMuscles: [.fullBody],
                     secondaryMuscles: [.cardio],
                     category: .hiit,
                     difficulty: .intermediate,
                     equipment: "Bodyweight",
                     iconName: "figure.mixed.cardio",
                     caloriesPerMinute: 12),

            Exercise(name: "Box Jump",
                     description: "Plyometric power exercise developing explosive leg strength.",
                     instructions: ["Stand facing box, feet hip-width",
                                    "Quarter squat and swing arms",
                                    "Explode upward, pulling knees up",
                                    "Land softly with bent knees",
                                    "Step down — don't jump down"],
                     tips: ["Always step down to protect knees", "Land with soft knees"],
                     primaryMuscles: [.quadriceps, .glutes],
                     secondaryMuscles: [.calves, .core],
                     category: .hiit,
                     difficulty: .intermediate,
                     equipment: "Plyo Box",
                     iconName: "figure.jumprope",
                     caloriesPerMinute: 10),
        ]
    }
}
