import Foundation

// MARK: - Functional Fitness Exercise Library (~35 exercises)
// Home/personal gym training: kettlebells, dumbbells, bodyweight, pull-up bar.
// Focus: compound movements, circuits, functional strength.

enum FunctionalFitnessSeedData {
    static func exercises() -> [Exercise] {
        return lowerBody() + upperBody() + core() + full() + conditioning()
    }

    // MARK: Lower Body (8)
    static func lowerBody() -> [Exercise] { [
        Exercise(name: "Goblet Squat",
                 description: "Dumbbell or kettlebell held at chest, squat to full depth. Great for all levels.",
                 instructions: ["Hold kettlebell/dumbbell at chest height", "Feet slightly wider than hips, toes out", "Squat deep, elbows track inside knees", "Drive up through heels"],
                 tips: ["Goblet position forces upright torso", "Excellent for knee and hip mobility"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Kettlebell", defaultSets: 4, defaultReps: 12,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 7.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Single-Leg Romanian Deadlift",
                 description: "Unilateral hip hinge for balance, hamstring strength and stability.",
                 instructions: ["Hold dumbbell in opposite hand to standing leg", "Hinge forward, kick free leg back", "Lower dumbbell toward floor", "Return to standing, squeeze glute"],
                 tips: ["Keep hips square throughout", "Look at a point on the floor for balance"],
                 primaryMuscles: [.hamstrings], secondaryMuscles: [.glutes, .core],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 10,
                 iconName: "dumbbell", caloriesPerMinute: 6.5,
                 archetype: .functionalFitness, workoutStyle: .setsAndReps),

        Exercise(name: "Bulgarian Split Squat",
                 description: "Rear foot elevated split squat — brutal quad and glute developer.",
                 instructions: ["Rear foot on bench or elevated surface", "Front foot forward enough for 90° knee bend", "Lower until rear knee near floor", "Drive up through front heel"],
                 tips: ["This is harder than it looks — start light", "Front knee tracks over middle toe"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 10,
                 iconName: "dumbbell", caloriesPerMinute: 7.5,
                 archetype: .functionalFitness, workoutStyle: .setsAndReps),

        Exercise(name: "Kettlebell Swing",
                 description: "Explosive hip hinge movement using a kettlebell. Builds power and conditions.",
                 instructions: ["Hinge at hips, swing kettlebell between legs", "Drive hips forward explosively", "Swing to chest height", "Let momentum pull back into hinge"],
                 tips: ["This is a HIP exercise, not a squat", "Power comes from hips not arms", "Brace at the top"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.hamstrings, .core, .shoulders],
                 category: .hiit, difficulty: .intermediate,
                 equipment: "Kettlebell", defaultSets: 4, defaultReps: 15,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 10.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Step-Up",
                 description: "Unilateral knee-dominant exercise using a box or bench.",
                 instructions: ["Place one foot fully on bench/box", "Drive through heel to stand on box", "Bring other foot to meet it", "Step back down with control"],
                 tips: ["Great knee-friendly alternative to squats", "Keep torso upright"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 6.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Lateral Lunge",
                 description: "Side-to-side movement targeting inner thighs, glutes and hip mobility.",
                 instructions: ["Step wide to one side", "Bend stepping knee, keep other leg straight", "Push hips back and down", "Drive back to center"],
                 tips: ["Excellent for hip mobility", "Load with dumbbell when bodyweight is easy"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 6.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Box Jump",
                 description: "Plyometric power movement. Jump onto a box and land softly.",
                 instructions: ["Stand in front of box", "Dip hips, swing arms", "Jump and land softly on box", "Step down, reset"],
                 tips: ["Land with bent knees to absorb impact", "Box should be 20-24\" for most people"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .calves],
                 category: .hiit, difficulty: .intermediate,
                 equipment: "Bodyweight", defaultSets: 4, defaultReps: 8,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 10.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Glute Bridge",
                 description: "Floor hip extension targeting glutes. Excellent for beginners and warm-ups.",
                 instructions: ["Lie on back, feet flat on floor, knees bent", "Drive hips up, squeeze glutes at top", "Hold a moment at peak", "Lower with control"],
                 tips: ["Push through heels not toes", "Double-leg is easier; elevate feet for harder"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.hamstrings, .core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 5.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),
    ] }

    // MARK: Upper Body (10)
    static func upperBody() -> [Exercise] { [
        Exercise(name: "Dumbbell Thruster",
                 description: "Front squat into overhead press — full body compound movement.",
                 instructions: ["Hold dumbbells at shoulders", "Squat down to parallel", "Drive up and press dumbbells overhead", "Lower dumbbells back to shoulders"],
                 tips: ["Use leg power to drive the press", "Core braced throughout"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.shoulders, .glutes, .core],
                 category: .hiit, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 4, defaultReps: 10,
                 iconName: "dumbbell", caloriesPerMinute: 10.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Pull-Up",
                 description: "Bodyweight back and bicep exercise. A functional fitness staple.",
                 instructions: ["Hang from bar with overhand grip", "Pull shoulder blades down and back", "Drive elbows to hips", "Lower with control"],
                 tips: ["Work toward strict form before adding reps", "Band-assisted is fine for beginners"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Pull-up Bar", defaultSets: 4, defaultReps: 8,
                 iconName: "arrow.up.circle", caloriesPerMinute: 7.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Ring Row",
                 description: "Inverted row using rings or TRX — scalable pulling exercise.",
                 instructions: ["Set rings at waist height", "Lean back, heels on floor", "Row chest to rings", "Extend arms under control"],
                 tips: ["More horizontal = harder", "Keep body rigid like a plank"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps, .core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 12,
                 iconName: "arrow.up.circle", caloriesPerMinute: 5.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Pike Push-Up",
                 description: "Bodyweight shoulder press progression with hips elevated.",
                 instructions: ["Start in downward dog position", "Lower head toward floor", "Press back up", "Maintain hip position throughout"],
                 tips: ["Gateway to handstand push-ups", "Elevated feet make it harder"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.triceps, .core],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 5.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Dumbbell Push Press",
                 description: "Overhead press with a leg drive assist — builds power and shoulder strength.",
                 instructions: ["Hold dumbbells at shoulders", "Dip knees slightly", "Drive legs and press dumbbells overhead", "Lower with control"],
                 tips: ["Use leg drive to move heavier weight than strict press", "Great for power development"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.triceps, .core],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell", caloriesPerMinute: 7.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Renegade Row",
                 description: "Dumbbell row from push-up position — core anti-rotation challenge.",
                 instructions: ["Start in push-up position with dumbbells", "Row one dumbbell to hip", "Keep hips square (don't rotate)", "Alternate sides"],
                 tips: ["Widen feet for more stability", "Lighter weight than regular rows"],
                 primaryMuscles: [.back], secondaryMuscles: [.core, .shoulders],
                 category: .strength, difficulty: .advanced,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 8,
                 iconName: "dumbbell", caloriesPerMinute: 7.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Resistance Band Pull-Apart",
                 description: "Rear delt and upper back exercise using a resistance band.",
                 instructions: ["Hold band in front at shoulder height", "Pull band apart until arms fully extended", "Squeeze shoulder blades", "Return slowly"],
                 tips: ["Simple but highly effective for shoulder health", "Great warm-up exercise"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.back],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Resistance Band", defaultSets: 3, defaultReps: 15,
                 iconName: "link", caloriesPerMinute: 3.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Dumbbell Clean and Press",
                 description: "Olympic-style full body movement: clean dumbbells to shoulders, press overhead.",
                 instructions: ["Hinge, dumbbells below knees", "Drive hips, pull dumbbells to shoulders", "Press overhead", "Lower to starting position"],
                 tips: ["Timing is key — hips power the clean", "Full body power expression"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.back, .quadriceps, .core],
                 category: .hiit, difficulty: .advanced,
                 equipment: "Dumbbells", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell", caloriesPerMinute: 10.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Bear Crawl",
                 description: "Full body movement pattern on hands and knees — builds core and shoulder stability.",
                 instructions: ["Start on all fours, knees hovering 2 inches off floor", "Move opposite hand and foot forward", "Stay low, keep back flat", "Crawl for distance or time"],
                 tips: ["Slower is harder than faster", "Keep your back table-flat"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders, .quadriceps],
                 category: .hiit, difficulty: .intermediate,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 30,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 8.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Burpee",
                 description: "Full body conditioning exercise combining squat thrust and jump.",
                 instructions: ["Stand, drop hands to floor", "Jump feet back to push-up position", "Do a push-up (optional)", "Jump feet forward, then jump up"],
                 tips: ["Pace yourself — these get tiring fast", "Scale by removing push-up or jump"],
                 primaryMuscles: [.fullBody], secondaryMuscles: [],
                 category: .hiit, difficulty: .intermediate,
                 equipment: "Bodyweight", defaultSets: 4, defaultReps: 10,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 12.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),
    ] }

    // MARK: Core (8)
    static func core() -> [Exercise] { [
        Exercise(name: "Dead Bug",
                 description: "Anti-extension core exercise maintaining neutral spine under movement.",
                 instructions: ["Lie on back, arms up, legs at 90°", "Simultaneously lower opposite arm and leg", "Keep lower back pressed to floor", "Return to start, alternate sides"],
                 tips: ["Quality over speed — this is controlled", "Don't let lower back arch"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 4.0,
                 archetype: .functionalFitness, workoutStyle: .setsAndReps),

        Exercise(name: "Plank",
                 description: "Isometric core stability exercise.",
                 instructions: ["Forearms on floor, elbows under shoulders", "Body in straight line from head to heels", "Hold without letting hips sag"],
                 tips: ["Squeeze glutes throughout", "Breathe steadily"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 45, defaultHoldSeconds: 45,
                 iconName: "figure.strengthtraining.traditional", caloriesPerMinute: 4.0,
                 archetype: .functionalFitness, workoutStyle: .timedHold),

        Exercise(name: "Hollow Body Hold",
                 description: "Gymnastics core exercise — foundational for all overhead and bodyweight work.",
                 instructions: ["Lie on back, lower back pressed to floor", "Raise arms overhead and legs off floor", "Hold the hollow position", "Arms and legs about 6 inches from floor"],
                 tips: ["If too hard, tuck knees", "Core gymnastics gold standard"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 30, defaultHoldSeconds: 30,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 4.5,
                 archetype: .functionalFitness, workoutStyle: .timedHold),

        Exercise(name: "Russian Twist",
                 description: "Rotational core exercise targeting obliques.",
                 instructions: ["Sit, feet off floor, lean back slightly", "Twist torso side to side", "Touch floor each side", "Add weight for progression"],
                 tips: ["Controlled rotation, not just arms", "Keep chest up"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 20,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 4.5,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Mountain Climbers",
                 description: "Dynamic core exercise in plank position — conditioning and core combined.",
                 instructions: ["Start in high plank", "Drive one knee toward chest", "Quickly alternate legs", "Maintain neutral spine throughout"],
                 tips: ["Slower = more core, faster = more cardio", "Keep hips level"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders],
                 category: .hiit, difficulty: .beginner,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 30,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 9.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),
    ] }

    // MARK: Full Body / Cardio (5)
    static func full() -> [Exercise] { [
        Exercise(name: "Kettlebell Turkish Get-Up",
                 description: "Complex full-body movement from lying to standing with a kettlebell overhead.",
                 instructions: ["Lie flat, kettlebell in one hand straight up", "Roll to elbow, then hand", "Sweep leg through to kneeling", "Stand up, reverse the motion"],
                 tips: ["Eyes on kettlebell at all times", "Very technical — learn without weight first"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders, .glutes],
                 category: .mobility, difficulty: .advanced,
                 equipment: "Kettlebell", defaultSets: 3, defaultReps: 3,
                 iconName: "figure.strengthtraining.functional", caloriesPerMinute: 7.0,
                 archetype: .functionalFitness, workoutStyle: .setsAndReps),

        Exercise(name: "Devil's Press",
                 description: "Dumbbell burpee into snatch — ultimate full body conditioning exercise.",
                 instructions: ["Burpee with dumbbells in hands", "Jump feet forward", "Hinge and snatch dumbbells overhead", "Lower and repeat"],
                 tips: ["Use the momentum from the jump in the snatch", "One of the hardest exercises — use light weight"],
                 primaryMuscles: [.fullBody], secondaryMuscles: [],
                 category: .hiit, difficulty: .advanced,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 6,
                 iconName: "dumbbell", caloriesPerMinute: 13.0,
                 archetype: .functionalFitness, workoutStyle: .amrap),
    ] }

    // MARK: Conditioning (4)
    static func conditioning() -> [Exercise] { [
        Exercise(name: "Jump Rope",
                 description: "Classic cardio and coordination exercise.",
                 instructions: ["Jump rope at moderate pace", "Land softly on balls of feet", "Keep elbows close to sides", "Maintain consistent rhythm"],
                 tips: ["Great warm-up or finisher", "Double-unders for advanced"],
                 primaryMuscles: [.cardio], secondaryMuscles: [.calves],
                 category: .cardio, difficulty: .beginner,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 60,
                 iconName: "figure.run", caloriesPerMinute: 10.0,
                 archetype: .functionalFitness, workoutStyle: .circuit),

        Exercise(name: "Sprint Interval",
                 description: "Short all-out sprints with rest. Builds conditioning and burns fat.",
                 instructions: ["Sprint at max effort for 20 seconds", "Rest for 40 seconds", "Repeat for prescribed rounds"],
                 tips: ["True max effort on each sprint", "Can be done on treadmill or outside"],
                 primaryMuscles: [.cardio], secondaryMuscles: [.quadriceps, .glutes],
                 category: .hiit, difficulty: .intermediate,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 20,
                 iconName: "figure.run", caloriesPerMinute: 14.0,
                 archetype: .functionalFitness, workoutStyle: .emom),
    ] }
}
