import Foundation

// MARK: - Gym Bro Exercise Library (~40 exercises)
// Classic gym training: barbells, dumbbells, cables, machines.
// Focus: hypertrophy, strength, push/pull/legs.

enum GymBroSeedData {
    static func exercises() -> [Exercise] {
        return chest() + back() + shoulders() + arms() + legs() + core()
    }

    // MARK: Chest (8)
    static func chest() -> [Exercise] { [
        Exercise(name: "Barbell Bench Press",
                 description: "The king of chest exercises. Lie on a flat bench, lower the bar to your chest and press it back up.",
                 instructions: ["Lie flat on bench, feet on floor", "Grip bar slightly wider than shoulder-width", "Unrack and lower slowly to mid-chest", "Drive bar back up explosively"],
                 tips: ["Keep shoulder blades retracted", "Don't bounce the bar off your chest", "Maintain a slight arch in lower back"],
                 primaryMuscles: [.chest], secondaryMuscles: [.shoulders, .triceps],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 7.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Incline Dumbbell Press",
                 description: "Upper chest emphasis. Press dumbbells on an incline bench.",
                 instructions: ["Set bench to 30-45°", "Hold dumbbells at shoulder level", "Press up and slightly inward", "Lower with control"],
                 tips: ["Don't flare elbows too wide", "Full range of motion builds upper chest"],
                 primaryMuscles: [.chest], secondaryMuscles: [.shoulders],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 10,
                 iconName: "dumbbell", caloriesPerMinute: 6.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Cable Chest Fly",
                 description: "Isolation fly using cable machine for constant tension through full range.",
                 instructions: ["Set cables to chest height", "Step forward with slight lean", "Bring handles together in arc motion", "Hold at peak contraction"],
                 tips: ["Keep elbows soft, not locked", "Feel the stretch at full extension"],
                 primaryMuscles: [.chest], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 12,
                 iconName: "cable.connector", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Dumbbell Fly",
                 description: "Classic chest isolation movement on a flat bench.",
                 instructions: ["Lie flat, dumbbells above chest", "Lower in wide arc to shoulder level", "Squeeze chest to return", "Keep slight elbow bend"],
                 tips: ["This is a stretch movement — don't go too heavy", "Feel the pec stretch at the bottom"],
                 primaryMuscles: [.chest], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 12,
                 iconName: "dumbbell", caloriesPerMinute: 5.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Weighted Dips",
                 description: "Upper body compound movement hitting chest and triceps.",
                 instructions: ["Use parallel bars or dip station", "Lean forward slightly for chest emphasis", "Lower until elbows at 90°", "Push back up through chest"],
                 tips: ["Lean more forward for chest, upright for triceps", "Add weight via belt when bodyweight is easy"],
                 primaryMuscles: [.chest], secondaryMuscles: [.triceps, .shoulders],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.strengthtraining.traditional", caloriesPerMinute: 7.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Machine Chest Press",
                 description: "Guided chest press on a machine — great for beginners or burn-out sets.",
                 instructions: ["Adjust seat so handles are at chest level", "Grip handles, elbows parallel to floor", "Press handles forward until arms extended", "Return slowly"],
                 tips: ["Good for drop sets and beginners learning the movement"],
                 primaryMuscles: [.chest], secondaryMuscles: [.triceps],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Machine", defaultSets: 3, defaultReps: 12,
                 iconName: "square.grid.2x2", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Decline Barbell Press",
                 description: "Targets the lower chest. Performed on a decline bench.",
                 instructions: ["Set bench to -15° to -30°", "Grip bar slightly wider than shoulders", "Lower to lower chest", "Press back up"],
                 tips: ["Make sure feet are secured under pad", "Lower chest emphasis"],
                 primaryMuscles: [.chest], secondaryMuscles: [.triceps],
                 category: .strength, difficulty: .advanced,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 7.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Push-Up",
                 description: "Classic bodyweight chest developer. No equipment needed.",
                 instructions: ["Start in high plank position", "Lower chest toward floor", "Keep elbows at ~45° angle", "Push back up to start"],
                 tips: ["Keep core tight throughout", "Full range of motion"],
                 primaryMuscles: [.chest], secondaryMuscles: [.triceps, .core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.strengthtraining.traditional", caloriesPerMinute: 6.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),
    ] }

    // MARK: Back (8)
    static func back() -> [Exercise] { [
        Exercise(name: "Barbell Deadlift",
                 description: "The ultimate posterior chain builder. Pull a loaded barbell from the floor.",
                 instructions: ["Stand with feet hip-width, bar over mid-foot", "Hinge at hips, grip bar just outside legs", "Brace core, drive through floor", "Lock hips and shoulders simultaneously"],
                 tips: ["Keep bar close to body throughout", "Never round lower back under load", "Hinge, don't squat"],
                 primaryMuscles: [.back], secondaryMuscles: [.glutes, .hamstrings, .core],
                 category: .strength, difficulty: .advanced,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 5,
                 iconName: "dumbbell.fill", caloriesPerMinute: 9.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Pull-Up",
                 description: "The gold standard for back width. Pull bodyweight from dead hang to chin over bar.",
                 instructions: ["Hang from bar with overhand grip", "Pull shoulder blades down and back", "Drive elbows toward hips", "Lower with control"],
                 tips: ["Full dead hang between reps builds more range", "Pronated grip hits lats harder"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Pull-up Bar", defaultSets: 4, defaultReps: 8,
                 iconName: "arrow.up.circle", caloriesPerMinute: 7.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Barbell Bent-Over Row",
                 description: "Mass-building back exercise. Hinge forward and row a barbell to your lower chest.",
                 instructions: ["Hinge forward ~45°, overhand grip", "Retract shoulder blades before pulling", "Row bar to lower chest/upper abdomen", "Lower slowly"],
                 tips: ["Braced core prevents lower back rounding", "Lead with elbows"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps, .core],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 7.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Lat Pulldown",
                 description: "Machine-based lat builder. Pulls the lat muscle through its full range.",
                 instructions: ["Sit with thighs under pad", "Grip bar wider than shoulders", "Pull bar to upper chest", "Return until arms fully extended"],
                 tips: ["Lean back slightly at bottom of pull", "Don't let shoulders shrug"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 12,
                 iconName: "cable.connector", caloriesPerMinute: 6.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Seated Cable Row",
                 description: "Horizontal pulling movement targeting mid-back and lats.",
                 instructions: ["Sit at cable station, feet on pads", "Row handle to abdomen", "Squeeze shoulder blades at peak", "Return under control"],
                 tips: ["Don't lean back and forward excessively — stay tall", "Vary grip for different emphasis"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 12,
                 iconName: "cable.connector", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Dumbbell Single-Arm Row",
                 description: "Unilateral back exercise allowing full range of motion and heavy loading.",
                 instructions: ["Place one knee and hand on bench", "Row dumbbell to hip height", "Keep elbow close to body", "Fully extend arm at bottom"],
                 tips: ["Think 'pull elbow to ceiling'", "Allow shoulder to protract at bottom for better stretch"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 10,
                 iconName: "dumbbell", caloriesPerMinute: 6.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Face Pull",
                 description: "Cable exercise for rear delts and upper back. Essential for shoulder health.",
                 instructions: ["Set cable to upper chest height", "Grip rope with overhand grip", "Pull to face level, elbows high", "Hold at peak contraction"],
                 tips: ["Use lighter weight — this is about tension not strength", "Great warm-up for upper body days"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.back],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 15,
                 iconName: "cable.connector", caloriesPerMinute: 4.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "T-Bar Row",
                 description: "Heavy compound rowing variation. Excellent for back thickness.",
                 instructions: ["Load one end of a barbell", "Straddle the bar, hinge forward", "Use V-handle or row grip", "Pull bar to chest"],
                 tips: ["Keep back flat — don't round", "Great for building back thickness"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .strength, difficulty: .advanced,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 7.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),
    ] }

    // MARK: Shoulders (5)
    static func shoulders() -> [Exercise] { [
        Exercise(name: "Overhead Barbell Press",
                 description: "The foundational shoulder press. Stand or sit and press a barbell overhead.",
                 instructions: ["Grip bar slightly wider than shoulders", "Bar rests on upper chest/front delts", "Press straight up, lock out overhead", "Lower to starting position"],
                 tips: ["Keep core braced throughout", "Don't lean back excessively", "Feet shoulder-width for stability"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.triceps, .core],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 6.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Dumbbell Lateral Raise",
                 description: "Isolation exercise for the lateral deltoid, creating shoulder width.",
                 instructions: ["Stand with dumbbells at sides", "Raise arms to shoulder level, elbows soft", "Lead with elbows, not hands", "Lower slowly"],
                 tips: ["Slight internal rotation hits the lateral head harder", "Use lighter weight with strict form"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 15,
                 iconName: "dumbbell", caloriesPerMinute: 4.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Arnold Press",
                 description: "Rotational dumbbell press hitting all three deltoid heads.",
                 instructions: ["Start with dumbbells at chin, palms facing you", "Rotate palms outward as you press up", "Finish with palms facing forward", "Reverse the motion on the way down"],
                 tips: ["The rotation is the key — don't rush it", "Full range of motion for all heads"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.triceps],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 12,
                 iconName: "dumbbell", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Rear Delt Fly",
                 description: "Targets the posterior deltoid — crucial for balanced shoulder development.",
                 instructions: ["Hinge forward or lie on an incline bench", "Hold dumbbells below chest", "Raise arms out to sides", "Squeeze rear delts at top"],
                 tips: ["Most people neglect rear delts — prioritize them", "Keep weight light for proper form"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [.back],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 15,
                 iconName: "dumbbell", caloriesPerMinute: 4.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Cable Lateral Raise",
                 description: "Cable version of lateral raise providing constant tension throughout.",
                 instructions: ["Stand beside cable with low pulley", "Cross-body grip on handle", "Raise arm to shoulder level", "Control the descent"],
                 tips: ["Constant tension is the advantage over dumbbells", "Single-arm allows full focus"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 15,
                 iconName: "cable.connector", caloriesPerMinute: 4.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),
    ] }

    // MARK: Arms (6)
    static func arms() -> [Exercise] { [
        Exercise(name: "Barbell Curl",
                 description: "Classic bicep builder using a barbell for maximum load.",
                 instructions: ["Stand with barbell, underhand grip", "Curl bar to shoulder level", "Squeeze bicep at top", "Lower slowly under control"],
                 tips: ["Don't swing body — isolate the bicep", "Full extension at the bottom"],
                 primaryMuscles: [.biceps], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Barbell", defaultSets: 3, defaultReps: 12,
                 iconName: "dumbbell.fill", caloriesPerMinute: 5.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Hammer Curl",
                 description: "Neutral grip curl targeting bicep brachii and brachialis for arm thickness.",
                 instructions: ["Hold dumbbells with neutral grip (thumbs up)", "Curl up keeping palms facing each other", "Squeeze at top", "Lower with control"],
                 tips: ["Great for forearm development too", "Can be done alternating or simultaneously"],
                 primaryMuscles: [.biceps], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 12,
                 iconName: "dumbbell", caloriesPerMinute: 5.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Incline Dumbbell Curl",
                 description: "Lying back on an incline for a stretched bicep position — great for peak.",
                 instructions: ["Sit on incline bench, dumbbells hanging at sides", "Curl both dumbbells, elbows stay back", "Squeeze hard at top", "Lower fully for complete stretch"],
                 tips: ["The incline stretch is the key benefit", "Don't let elbows drift forward"],
                 primaryMuscles: [.biceps], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 10,
                 iconName: "dumbbell", caloriesPerMinute: 4.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Skull Crusher",
                 description: "Tricep isolation using an EZ bar lying on a bench.",
                 instructions: ["Lie on bench, EZ bar overhead", "Lower bar toward forehead by bending elbows", "Keep upper arms vertical", "Extend back to start"],
                 tips: ["Elbows should not flare out", "Control the descent — hence 'skull crusher'"],
                 primaryMuscles: [.triceps], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "EZ Bar", defaultSets: 3, defaultReps: 12,
                 iconName: "dumbbell.fill", caloriesPerMinute: 5.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Cable Tricep Pushdown",
                 description: "Cable isolation for the tricep using a rope or bar attachment.",
                 instructions: ["Set cable to high position", "Grip rope/bar with overhand grip", "Push down extending elbows fully", "Return to 90° angle"],
                 tips: ["Keep upper arms locked to sides", "Spread rope at bottom for a harder contraction"],
                 primaryMuscles: [.triceps], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 15,
                 iconName: "cable.connector", caloriesPerMinute: 4.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Close-Grip Bench Press",
                 description: "Compound tricep movement using a close grip on the barbell.",
                 instructions: ["Grip bar shoulder-width (not too narrow)", "Lower bar to lower chest", "Press up, elbows close to sides", "Full lock-out at top"],
                 tips: ["Elbows too close can stress wrists — shoulder-width is fine", "Heavier than isolation work"],
                 primaryMuscles: [.triceps], secondaryMuscles: [.chest],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 6.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),
    ] }

    // MARK: Legs (8)
    static func legs() -> [Exercise] { [
        Exercise(name: "Barbell Back Squat",
                 description: "The king of leg exercises. Barbell on upper back, squat to parallel.",
                 instructions: ["Bar on upper traps, feet shoulder-width", "Brace core, initiate with hips", "Descend to parallel or below", "Drive through heels to stand"],
                 tips: ["Chest up throughout", "Knees track over toes", "Depth before weight"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .hamstrings, .core],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 8,
                 iconName: "dumbbell.fill", caloriesPerMinute: 9.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Romanian Deadlift",
                 description: "Hip hinge movement targeting hamstrings and glutes. Loaded stretch.",
                 instructions: ["Hold barbell at hips", "Hinge forward, slight knee bend", "Lower bar along legs until hamstring stretch", "Drive hips forward to stand"],
                 tips: ["Feel the hamstring stretch — that's the point", "Keep bar close to body", "Don't round back"],
                 primaryMuscles: [.hamstrings], secondaryMuscles: [.glutes, .back],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 10,
                 iconName: "dumbbell.fill", caloriesPerMinute: 7.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Leg Press",
                 description: "Machine-based quad exercise allowing heavy loading safely.",
                 instructions: ["Place feet shoulder-width on platform", "Lower platform until knees at 90°", "Press platform back to start", "Don't lock knees fully"],
                 tips: ["Foot position changes emphasis — high=glutes, low=quads", "Don't let lower back lift off pad"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Machine", defaultSets: 4, defaultReps: 12,
                 iconName: "square.grid.2x2", caloriesPerMinute: 7.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Hip Thrust",
                 description: "Glute isolation powerhouse. Drive hips up against a barbell.",
                 instructions: ["Sit against bench, barbell over hips", "Plant feet firmly, push hips up", "Squeeze glutes hard at top", "Lower hips toward floor"],
                 tips: ["Use a barbell pad for comfort", "Full hip extension at the top"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.hamstrings],
                 category: .hypertrophy, difficulty: .intermediate,
                 equipment: "Barbell", defaultSets: 4, defaultReps: 12,
                 iconName: "dumbbell.fill", caloriesPerMinute: 7.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Leg Curl",
                 description: "Machine isolation exercise for the hamstrings.",
                 instructions: ["Lie face down on machine", "Position roller just above ankles", "Curl legs toward glutes", "Lower with control"],
                 tips: ["Don't let hips lift off pad", "Full range of motion"],
                 primaryMuscles: [.hamstrings], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Machine", defaultSets: 3, defaultReps: 12,
                 iconName: "square.grid.2x2", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Leg Extension",
                 description: "Quad isolation on a machine. Good for burn-out sets and finishers.",
                 instructions: ["Sit in machine, pad at ankle level", "Extend legs to fully straight", "Squeeze quads hard at top", "Lower slowly"],
                 tips: ["Great as a finisher after squats", "Don't use excessive weight"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Machine", defaultSets: 3, defaultReps: 15,
                 iconName: "square.grid.2x2", caloriesPerMinute: 5.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Walking Lunges",
                 description: "Dynamic leg exercise hitting quads, glutes and hamstrings.",
                 instructions: ["Hold dumbbells at sides", "Step forward into lunge position", "Lower back knee toward floor", "Drive forward with front leg"],
                 tips: ["Keep torso upright", "Step far enough that knee doesn't track over toes"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .hamstrings],
                 category: .strength, difficulty: .beginner,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 12,
                 iconName: "dumbbell", caloriesPerMinute: 7.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Seated Calf Raise",
                 description: "Machine calf isolation targeting the soleus specifically.",
                 instructions: ["Sit at machine, pads on lower thighs", "Raise heels as high as possible", "Hold at peak contraction", "Lower heels below platform level"],
                 tips: ["Soleus responds to higher reps", "Full stretch at the bottom"],
                 primaryMuscles: [.calves], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Machine", defaultSets: 4, defaultReps: 15,
                 iconName: "square.grid.2x2", caloriesPerMinute: 4.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),
    ] }

    // MARK: Core (4)
    static func core() -> [Exercise] { [
        Exercise(name: "Cable Crunch",
                 description: "Weighted ab exercise for developing thick, defined core musculature.",
                 instructions: ["Kneel at cable machine, rope overhead", "Pull elbows to knees, rounding spine", "Squeeze abs hard at bottom", "Return to upright under control"],
                 tips: ["Think about bringing ribs to pelvis", "This is NOT a lat pulldown"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Cable Machine", defaultSets: 3, defaultReps: 15,
                 iconName: "cable.connector", caloriesPerMinute: 5.0,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Hanging Leg Raise",
                 description: "Advanced ab exercise hanging from a pull-up bar.",
                 instructions: ["Hang from bar with overhand grip", "Raise legs to hip level (bent) or 90° (straight)", "Control the descent", "Avoid swinging"],
                 tips: ["For lower abs specifically", "Tuck knees to chest for easier variation"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Pull-up Bar", defaultSets: 3, defaultReps: 12,
                 iconName: "arrow.up.circle", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Ab Wheel Rollout",
                 description: "Highly effective anti-extension core exercise.",
                 instructions: ["Kneel on floor, grip ab wheel", "Roll forward until body parallel to floor", "Use abs to pull yourself back", "Don't let lower back sag"],
                 tips: ["Start with partial range if too hard", "One of the most effective core exercises"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders],
                 category: .strength, difficulty: .advanced,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 10,
                 iconName: "circle", caloriesPerMinute: 5.5,
                 archetype: .gymBro, workoutStyle: .setsAndReps),

        Exercise(name: "Plank",
                 description: "Isometric core stability exercise.",
                 instructions: ["Forearms on floor, elbows under shoulders", "Body in straight line head to heels", "Hold position, breathing normally", "Don't let hips sag"],
                 tips: ["Squeeze glutes and abs throughout", "Look slightly forward, not down"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight",
                 defaultDurationSeconds: 60, defaultHoldSeconds: 60,
                 iconName: "figure.strengthtraining.traditional", caloriesPerMinute: 4.0,
                 archetype: .gymBro, workoutStyle: .timedHold),
    ] }
}
