import Foundation

// MARK: - Pilates & Yoga Exercise Library (~35 exercises)
// Focus: toning, flexibility, core strength, controlled movement.
// Equipment: yoga mat, resistance bands, light dumbbells, bodyweight.

enum PilatesYogaSeedData {
    static func exercises() -> [Exercise] {
        return core() + lowerBody() + upperBody() + flexibility() + yogaFlows()
    }

    // MARK: Core & Pilates (10)
    static func core() -> [Exercise] { [
        Exercise(name: "The Hundred",
                 description: "Classic Pilates warm-up. Pump arms while holding legs at table-top.",
                 instructions: ["Lie flat, lift head and shoulders", "Raise legs to 45° or table-top", "Pump arms up and down in small pulses", "Inhale for 5 pumps, exhale for 5 pumps"],
                 tips: ["Lower legs = harder on core", "Keep neck long, not strained", "100 pumps total"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultDurationSeconds: 60,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 4.5,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Single Leg Circle",
                 description: "Pilates movement for hip mobility and core control.",
                 instructions: ["Lie flat, one leg extended up", "Circle the raised leg, keeping hips still", "Make controlled circles both directions", "Alternate legs"],
                 tips: ["The still hip is the key", "Start with small circles, progress to larger"],
                 primaryMuscles: [.core], secondaryMuscles: [.glutes],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 8,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Rolling Like a Ball",
                 description: "Massage for the spine and core activation. Roll back and balance.",
                 instructions: ["Sit holding knees to chest", "Balance on sit bones", "Roll back to shoulder blades", "Roll back up to balance — don't go to neck"],
                 tips: ["Curl spine like a C", "Don't roll onto neck"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 2, defaultReps: 10,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.0,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Pilates Crunch",
                 description: "Small range of motion crunch with precision and core control.",
                 instructions: ["Lie flat, knees bent, hands behind head", "Inhale to prepare", "Exhale, curl head and shoulders off mat", "Hold at top, lower slowly"],
                 tips: ["Quality over quantity", "Don't pull on neck", "Exhale fully at the top"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Plank to Downward Dog",
                 description: "Dynamic flow between plank and downward facing dog.",
                 instructions: ["Start in high plank", "Push hips up and back into downward dog", "Hold a breath in downward dog", "Return to plank"],
                 tips: ["Feel the hamstring stretch in downward dog", "Press through palms evenly"],
                 primaryMuscles: [.core], secondaryMuscles: [.shoulders, .hamstrings],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 4.0,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Side-Lying Leg Lift",
                 description: "Pilates outer thigh and glute med isolation lying on side.",
                 instructions: ["Lie on side, body in straight line", "Raise top leg to 45°", "Lower with control", "Don't rock pelvis"],
                 tips: ["Hips stacked, not rolling forward", "Add resistance band for progression"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Bird Dog",
                 description: "Core stability exercise on all fours. Anti-rotation and balance.",
                 instructions: ["Start on hands and knees", "Extend opposite arm and leg simultaneously", "Hold 3 seconds at full extension", "Return and alternate"],
                 tips: ["Keep back flat — don't rotate hips", "Slow and controlled"],
                 primaryMuscles: [.core], secondaryMuscles: [.glutes, .shoulders],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 10,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Teaser",
                 description: "Advanced Pilates V-sit movement. Full core integration.",
                 instructions: ["Lie flat, legs extended", "Inhale to prepare", "Exhale, peel spine off mat into V-position", "Balance on sit bones, arms parallel to legs"],
                 tips: ["Curl slowly — segment by segment", "Advanced — keep knees bent if needed"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .advanced,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 8,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 5.0,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Boat Pose Hold",
                 description: "Yoga V-sit balance for core strength and hip flexor flexibility.",
                 instructions: ["Sit with knees bent, feet off floor", "Lean back to 45°, balance on sit bones", "Extend arms forward parallel to floor", "Hold the position breathing steadily"],
                 tips: ["Straight legs = harder, bent = easier", "Keep back long, not rounded"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 30,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 4.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Side Plank",
                 description: "Lateral core stability. Targets obliques and hip abductors.",
                 instructions: ["Lie on side, prop on forearm", "Lift hips off floor in straight line", "Hold position", "Lower and switch sides"],
                 tips: ["Stack feet or stagger for easier", "Hip shouldn't sag"],
                 primaryMuscles: [.core], secondaryMuscles: [],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 30,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 4.0,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),
    ] }

    // MARK: Lower Body (8)
    static func lowerBody() -> [Exercise] { [
        Exercise(name: "Sumo Squat",
                 description: "Wide stance squat with toes turned out. Hits inner thighs and glutes.",
                 instructions: ["Stand wide, toes pointed out 45°", "Squat keeping knees over toes", "Squeeze inner thighs at the top", "Add dumbbell held at centre for load"],
                 tips: ["Inner thigh activation is the goal", "Stay tall through the spine"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 5.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Resistance Band Clamshell",
                 description: "Hip abductor exercise with resistance band. Glute med activation.",
                 instructions: ["Lie on side, band above knees", "Feet together, knees at 90°", "Rotate top knee upward like a clamshell", "Lower with control"],
                 tips: ["Don't rock the pelvis", "Glute med is weak in most people — this helps"],
                 primaryMuscles: [.glutes], secondaryMuscles: [],
                 category: .strength, difficulty: .beginner,
                 equipment: "Resistance Band", defaultSets: 3, defaultReps: 15,
                 iconName: "link", caloriesPerMinute: 3.0,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Donkey Kick",
                 description: "Glute isolation on all fours. Simple and effective for toning.",
                 instructions: ["Start on all fours", "Kick one leg back and up, knee at 90°", "Squeeze glute hard at top", "Lower and repeat"],
                 tips: ["Don't rotate hips", "Slow and controlled is key"],
                 primaryMuscles: [.glutes], secondaryMuscles: [],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Banded Hip Thrust",
                 description: "Glute-dominant hip extension with resistance band for constant tension.",
                 instructions: ["Sit against couch/bench, band above knees", "Plant feet, drive hips up", "Squeeze glutes hard at top", "Lower slowly"],
                 tips: ["Band adds glute med recruitment", "Push knees out against band"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.hamstrings],
                 category: .strength, difficulty: .intermediate,
                 equipment: "Resistance Band", defaultSets: 4, defaultReps: 15,
                 iconName: "link", caloriesPerMinute: 5.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Low Squat Hold (Yogi Squat)",
                 description: "Deep squat hold for hip mobility and ankle flexibility.",
                 instructions: ["Stand feet wider than shoulder width", "Squat as deep as possible", "Press elbows against inner knees", "Hold breathing deeply"],
                 tips: ["Elevate heels if ankles are tight", "One of the best hip openers"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .core],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Bodyweight",
                 defaultHoldSeconds: 60,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.0,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Pilates Bridge",
                 description: "Articulating bridge — peel spine off mat vertebra by vertebra.",
                 instructions: ["Lie flat, feet hip-width, knees bent", "Inhale to prepare", "Exhale, peel spine from tailbone to shoulders", "Hold at top, then roll back down"],
                 tips: ["Articulation is the key — don't just lift hips", "Think of imprinting each vertebra"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.hamstrings, .core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Yoga Mat", defaultSets: 3, defaultReps: 12,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 4.0,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Fire Hydrant",
                 description: "Hip abduction and external rotation on all fours.",
                 instructions: ["Start on all fours", "Raise one knee out to side, keeping 90° bend", "Raise to hip height", "Lower and repeat"],
                 tips: ["Don't rotate spine", "Resistance band above knees adds challenge"],
                 primaryMuscles: [.glutes], secondaryMuscles: [],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 15,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Wall Sit",
                 description: "Isometric quad strengthener and endurance challenge.",
                 instructions: ["Back flat against wall", "Slide down until knees at 90°", "Hold position", "Keep weight in heels"],
                 tips: ["Don't let knees cave in", "Breathe through the burn"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight",
                 defaultHoldSeconds: 45,
                 iconName: "figure.stand", caloriesPerMinute: 4.0,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),
    ] }

    // MARK: Upper Body (4)
    static func upperBody() -> [Exercise] { [
        Exercise(name: "Resistance Band Row",
                 description: "Seated or standing band row for back and postural muscles.",
                 instructions: ["Anchor band at chest height or sit with band around feet", "Row handles to sides of chest", "Squeeze shoulder blades together", "Control return"],
                 tips: ["Great for posture correction", "Feel the upper back squeeze"],
                 primaryMuscles: [.back], secondaryMuscles: [.biceps],
                 category: .strength, difficulty: .beginner,
                 equipment: "Resistance Band", defaultSets: 3, defaultReps: 15,
                 iconName: "link", caloriesPerMinute: 4.0,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Tricep Dip (Chair)",
                 description: "Bodyweight tricep exercise using a chair.",
                 instructions: ["Hands on edge of chair, legs extended", "Lower body bending elbows to 90°", "Press back up", "Keep elbows tracking back"],
                 tips: ["Straight legs = harder", "Keep shoulders down, not shrugged"],
                 primaryMuscles: [.triceps], secondaryMuscles: [.shoulders],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 12,
                 iconName: "figure.strengthtraining.traditional", caloriesPerMinute: 4.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Dumbbell Lateral Raise",
                 description: "Light dumbbell raises for shoulder toning and definition.",
                 instructions: ["Hold light dumbbells at sides", "Raise arms to shoulder level", "Lower with control", "Keep slight bend in elbows"],
                 tips: ["Use lighter weight than you think", "Slow tempo maximizes tension"],
                 primaryMuscles: [.shoulders], secondaryMuscles: [],
                 category: .hypertrophy, difficulty: .beginner,
                 equipment: "Dumbbells", defaultSets: 3, defaultReps: 15,
                 iconName: "dumbbell", caloriesPerMinute: 4.0,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),

        Exercise(name: "Push-Up",
                 description: "Bodyweight push-up for chest, shoulder and tricep toning.",
                 instructions: ["High plank position", "Lower chest toward floor", "Press back up", "Modify on knees if needed"],
                 tips: ["Knee push-ups are not cheating — they build strength", "Keep core tight"],
                 primaryMuscles: [.chest], secondaryMuscles: [.triceps, .core],
                 category: .strength, difficulty: .beginner,
                 equipment: "Bodyweight", defaultSets: 3, defaultReps: 12,
                 iconName: "figure.strengthtraining.traditional", caloriesPerMinute: 5.5,
                 archetype: .pilatesYoga, workoutStyle: .setsAndReps),
    ] }

    // MARK: Flexibility (5)
    static func flexibility() -> [Exercise] { [
        Exercise(name: "Seated Forward Fold",
                 description: "Hamstring and lower back stretch. Fundamental yoga pose.",
                 instructions: ["Sit with legs extended", "Inhale to lengthen spine", "Exhale, hinge forward from hips", "Reach toward feet, hold"],
                 tips: ["Bend knees slightly if hamstrings are tight", "Focus on lengthening, not rounding"],
                 primaryMuscles: [.hamstrings], secondaryMuscles: [.back],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 45,
                 iconName: "figure.flexibility", caloriesPerMinute: 2.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Pigeon Pose",
                 description: "Deep hip opener targeting the hip external rotators. Life-changing for tight hips.",
                 instructions: ["From downward dog, bring one leg forward, knee near wrist", "Extend other leg back", "Square hips toward mat", "Walk hands forward and rest"],
                 tips: ["Support hip with block if needed", "Breathe into the tightness"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.hamstrings],
                 category: .mobility, difficulty: .intermediate,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 60,
                 iconName: "figure.flexibility", caloriesPerMinute: 2.0,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Low Lunge (Crescent)",
                 description: "Hip flexor stretch and quad opener in a lunge position.",
                 instructions: ["Step one foot forward into lunge", "Lower back knee to mat", "Raise arms overhead", "Sink hips forward and down"],
                 tips: ["Feel the stretch in the back hip flexor", "Keep front knee over ankle"],
                 primaryMuscles: [.glutes], secondaryMuscles: [.quadriceps, .core],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 45,
                 iconName: "figure.flexibility", caloriesPerMinute: 2.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Thread the Needle",
                 description: "Upper back and shoulder rotation stretch on all fours.",
                 instructions: ["Start on all fours", "Slide one arm under body, rotating thoracic spine", "Rest ear on mat", "Hold, then return"],
                 tips: ["Great for thoracic mobility", "Keep hips still"],
                 primaryMuscles: [.back], secondaryMuscles: [.shoulders],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 30,
                 iconName: "figure.flexibility", caloriesPerMinute: 2.0,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Supine Twist",
                 description: "Lying spinal rotation for back release and oblique stretch.",
                 instructions: ["Lie flat, bring one knee to chest", "Guide knee across body with opposite hand", "Extend same-side arm out", "Look away from knee"],
                 tips: ["Both shoulders stay on mat ideally", "Breathe deeply into the twist"],
                 primaryMuscles: [.back], secondaryMuscles: [.core],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 45,
                 iconName: "figure.flexibility", caloriesPerMinute: 2.0,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),
    ] }

    // MARK: Yoga Flows (5)
    static func yogaFlows() -> [Exercise] { [
        Exercise(name: "Sun Salutation A",
                 description: "Classic vinyasa warm-up sequence flowing through mountain pose to downward dog.",
                 instructions: ["Mountain pose → arms overhead", "Forward fold → half lift", "High plank → chaturanga → upward dog", "Downward dog → step/jump to front → stand"],
                 tips: ["Sync breath to movement", "Each inhale lengthens, each exhale deepens"],
                 primaryMuscles: [.fullBody], secondaryMuscles: [],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultDurationSeconds: 120,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 5.0,
                 archetype: .pilatesYoga, workoutStyle: .flowSequence),

        Exercise(name: "Warrior I",
                 description: "Standing yoga pose building leg strength and hip flexibility.",
                 instructions: ["Lunge stance, back foot at 45°", "Square hips toward front", "Arms raised overhead", "Hold steady, breathe"],
                 tips: ["Back heel grounded", "Shoulders away from ears"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .core, .shoulders],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 45,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Warrior II",
                 description: "Wide-legged yoga pose with arms extended in opposite directions.",
                 instructions: ["Wide stance, front foot forward, back foot parallel", "Bend front knee over ankle", "Arms extended parallel to floor", "Gaze over front fingertips"],
                 tips: ["Front knee doesn't collapse inward", "Keep torso upright, not leaning forward"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .core],
                 category: .mobility, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 45,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 3.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Chair Pose",
                 description: "Yoga squat pose building leg endurance and core strength.",
                 instructions: ["Feet together or hip-width", "Bend knees as if sitting in chair", "Arms raised overhead", "Hold and breathe"],
                 tips: ["Sit deeper as you build endurance", "Weight in heels"],
                 primaryMuscles: [.quadriceps], secondaryMuscles: [.glutes, .core, .shoulders],
                 category: .strength, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 45,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 4.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),

        Exercise(name: "Child's Pose",
                 description: "Restorative yoga pose for back release and rest.",
                 instructions: ["Kneel, sink hips to heels", "Reach arms forward on mat", "Rest forehead down", "Breathe deeply"],
                 tips: ["Use as rest between harder poses", "Widen knees if belly gets in the way"],
                 primaryMuscles: [.back], secondaryMuscles: [.glutes],
                 category: .recovery, difficulty: .beginner,
                 equipment: "Yoga Mat",
                 defaultHoldSeconds: 60,
                 iconName: "figure.mind.and.body", caloriesPerMinute: 1.5,
                 archetype: .pilatesYoga, workoutStyle: .timedHold),
    ] }
}
